# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "The Little Eye"
  identifier = "blog"
  weight = 20

[[main]]
  parent = "blog"
  name = "Blog Posts"
  url = "the-little-eye"
  weight = 10

[[main]]
  parent = "blog"
  name = "Microscopy Timeline"
  url = "timeline"
  weight = 20

[[main]]
  name = "Research"
  identifier = "research"
  weight = 30

[[main]]
  parent = "research"
  name = "Projects"
  url = "research"
  weight = 10

[[main]]
  parent = "research"
  name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Training"
  url = "training"
  identifier = "training"
  weight = 40

[[main]]
  parent = "training"
  name = "Training"
  url = "training"
  weight = 10

[[main]]
  parent = "training"
  name = "Python Beginners' Course"
  url = "python"
  weight = 20

[[main]]
  parent = "training"
  name = "Bioimage Processing in Python"
  url = "impython"
  weight = 30

[[main]]
  parent = "training"
  name = "Bioimage Analysis in Python"
  url = "bapython"
  weight = 40

[[main]]
  name = "Engagement"
  url = "engagement"
  identifier = "engagement"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  identifier = "contact"
  weight = 100

[[main]]
parent = "contact"
  name = "Contact Form"
  url = "#contact"
  weight = 10

[[main]]
  parent = "contact"
  name = "CV"
  url = "files/cjn-cv.pdf"
  weight = 20
