baseURL: ""
title: Chas Nelson
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Chas Nelson
  description: "Chas Nelson"
  author: Chas Nelson
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false
  images: ["cjn.jpg"]

  profileMode:
    enabled: true # needs to be explicitly set
    title: Chas Nelson
    imageUrl: "cjn.jpg"
    imageTitle: Chas Nelson
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      # - name: Python Training
      #   url: training
      # - name: Archived Posts
      #   url: archives
      - name: Contact
        url: contact
    subtitle: >
      Chartered Biologist & PhD data scientist  

      focussed on how data can help us reach [Sustainable Development Goals](https://www.un.org/sustainabledevelopment/sustainable-development-goals/) 🇺🇳.  

      <br/>
      Founder, Director & Chief Technology Officer @ [gliff.ai](https://gliff.ai).  

      Honorary Research Fellow @ [University of Glasgow](https://www.gla.ac.uk/schools/physics/staff/chasnelson/).  

      Consultant Data Scientist @ [Fjelltopp](https://www.fjelltopp.org/).  

      Depute Chair (Policy) @ [Royal Society of Biology](https://www.rsb.org.uk/) in Scotland.  


      Data Analysis in Imaging Deputy Chair @ [Royal Microscopical Society](https://www.rms.org.uk/community/science-sections/image-analysis.html).  

      <br/>

  socialIcons:
    - name: email
      url: "mailto:#"
    - name: twitter
      url: "https://twitter.com/ChasNelson1990"
    - name: github
      url: "https://github.com/ChasNelson1990"
    - name: linkedin
      url: "https://linkedin.com/in/ChasNelson1990"
    - name: medium
      url: "https://medium.com/@ChasNelson1990"
    - name: googlescholar
      url: "https://scholar.google.com/citations?hl=en&user=lYGU2EoAAAAJ"
    - name: CV
      url: "cjn-cv.pdf"

markup:
  goldmark:
    renderer:
      unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai
