theme = "awesome-identity"
baseURL = ""
title = "Chas Nelson - Data Scientist / Chartered Biologist / Technology Leader"

languageCode = "en-gb"
# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = true
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true


## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
  description = "Chartered Biologist and PhD data scientist focussed on using data to change the world for the better"
  keywords = "Chas, Chas Nelson, data, scientist, biologist, engineer, developer, leader, technology, ChasNelson1990"
  images = [
    "cjn.jpg"
  ]

## Profile Configurations
[params.profile]
  portrait = "cjn.jpg"
  firstname = "Dr"
  lastname = "Chas Nelson"
  title = "Data Consultant · Chartered Biologist"
  bio = """
Data scientist and engineer focused on using data and technology to change the world for the better.
10+ years experience in data for life sciences including data-driven public health insights, academic research in biomedicine, and AI for MedTech.
Driven by creating sustainable transformation and development through data and technology.
<br/>
<br/>
Data Consultant @ [Fjelltopp](https://www.fjelltopp.org/).  
Technical Consultant @ [FAO Bangladesh](https://www.fao.org/bangladesh/en/).  
Depute Chair (Policy) @ [Royal Society of Biology](https://www.rsb.org.uk/) in Scotland.  
Data Analysis in Imaging Deputy Chair @ [Royal Microscopical Society](https://www.rms.org.uk/community/science-sections/image-analysis.html).  
<br/>
<br/>
Available for data science, data engineering, and data consultancy projects in the UK and internationally.  
Also available for public speaking, workshops, and training.
"""

## Contacts Configurations
[params.contacts]
  github = "ChasNelson1990"
  twitter = "ChasNelson1990"
  linkedin = "ChasNelson1990"
  medium = "@ChasNelson1990"
  gscholar = "lYGU2EoAAAAJ"


## Actions Configurations
[[params.actions]]
  name = "Contact Me"
  url = "contact"
[[params.actions]]
  name = "CV"
  url = "cjn-cv.pdf"


## Footer Configurations
[params.footer]
  copyright = "© 2023 Chas Nelson"
  poweredBy = true

[markup.goldmark.renderer]
  unsafe = true
