name: Deploy Site

on:
  push:
    branches:
      - master
  pull_request:
    branched:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.65.3
          TARGET_REPO: ChasNelson1990/chasnelson.co.uk_public
          TOKEN: ${{ secrets.PAK }}
          HUGO_ARGS: '--debug'
          CNAME: www.chasnelson.co.uk