name: Deploy Site

on:
  push:
    branches:
      - master
  pull_request:
    branched:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.57.2
          TARGET_REPO: ChasNelson1990/chasnelson.co.uk_public
          TOKEN: ${{ secrets.pak }}
          HUGO_ARGS: '-t academic'
          CNAME: chasnelson.co.uk